# This is a basic workflow to help you get started with Actions

name: UI Tests

on: [push]

jobs:
  # This workflow contains a single job called "build"
  chrome-ui-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        # run all tests
      - name: 'All Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install-command: npm install
          run: npx cypress run
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
            
